import React from 'react';
import { Sparkles } from 'lucide-react';

const ScoreBar = ({ score }) => {
  let colorClass = "bg-green-500";
  if (score < 5) colorClass = "bg-red-500";
  else if (score < 8) colorClass = "bg-amber-400";

  return (
    <div className="w-full bg-slate-100 rounded-full h-2.5 mt-2">
      <div className={`${colorClass} h-2.5 rounded-full transition-all`} style={{ width: `${(score / 10) * 100}%` }}></div>
    </div>
  );
};

const CategoryCard = ({ title, data }) => (
  <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm hover:shadow-md transition-shadow">
    <div className="flex justify-between items-center mb-3">
      <h3 className="font-bold text-lg text-slate-800 capitalize">{title.replace('_', ' ')}</h3>
      <div className="flex items-center gap-2">
        <span className="text-lg font-extrabold text-slate-800">{data.score}</span>
        <span className="text-xs text-slate-400">/ 10</span>
      </div>
    </div>
    <ScoreBar score={data.score} />
    <p className="mt-4 text-sm text-slate-600 font-medium">
      {data.summary}
    </p>
    <ul className="mt-4 space-y-2">
      {data.findings.map((finding, idx) => (
        <li key={idx} className="flex items-start text-sm text-slate-600">
          <span className="text-blue-500 mr-2 mt-0.5">•</span>
          <span>{finding}</span>
        </li>
      ))}
    </ul>
  </div>
);

const InsightsPanel = ({ insights }) => {
  const categories = [
    { key: 'seo_analysis', label: 'SEO Analysis' },
    { key: 'messaging_clarity', label: 'Messaging Clarity' },
    { key: 'cta_analysis', label: 'CTA Effectiveness' },
    { key: 'content_depth', label: 'Content Depth' },
    { key: 'ux_concerns', label: 'UX & Performance' }
  ];

  return (
    <section>
      <div className="mb-4">
        <h2 className="text-lg font-bold text-slate-800 flex items-center">
          <Sparkles className="w-5 h-5 mr-2 text-indigo-600" />
          AI Analysis
        </h2>
        <p className="text-sm text-slate-500">Generated by Claude 3.5 Sonnet</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {categories.map((cat) => (
          <CategoryCard 
            key={cat.key} 
            title={cat.label} 
            data={insights[cat.key]} 
          />
        ))}
      </div>
    </section>
  );
};

export default InsightsPanel;
